/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.totserapp.view;

/**
 *
 * @author Ivan_
 */
public class ValoracioView extends View {
    private int sel;
    /**
     * Creates new form ValoracioView
     */
    public ValoracioView(String episodi, int selected){
        initComponents();
        this.sel=selected;
        this.setTitle(episodi);
        this.radbtn_1.setVisible(false);
        this.radbtn_2.setVisible(false);
        this.radbtn_3.setVisible(false);
        this.radbtn_4.setVisible(false);
        this.radbtn_5.setVisible(false);
    }

    private ValoracioView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_group = new javax.swing.ButtonGroup();
        btn_yes_accept = new javax.swing.JButton();
        btn_no_cancel = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        radbtn_1 = new javax.swing.JRadioButton();
        radbtn_2 = new javax.swing.JRadioButton();
        radbtn_3 = new javax.swing.JRadioButton();
        radbtn_4 = new javax.swing.JRadioButton();
        radbtn_5 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        btn_yes_accept.setText("Si");
        btn_yes_accept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_yes_acceptActionPerformed(evt);
            }
        });

        btn_no_cancel.setText("No");
        btn_no_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_no_cancelActionPerformed(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Vols valorar l'episodi?");

        btn_group.add(radbtn_1);
        radbtn_1.setText("1");

        btn_group.add(radbtn_2);
        radbtn_2.setText("2");

        btn_group.add(radbtn_3);
        radbtn_3.setText("3");

        btn_group.add(radbtn_4);
        radbtn_4.setText("4");

        btn_group.add(radbtn_5);
        radbtn_5.setText("5");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(btn_yes_accept)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_no_cancel)
                .addGap(103, 103, 103))
            .addGroup(layout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addComponent(radbtn_1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radbtn_2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radbtn_3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radbtn_4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radbtn_5)
                .addContainerGap(148, Short.MAX_VALUE))
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radbtn_1)
                    .addComponent(radbtn_2)
                    .addComponent(radbtn_3)
                    .addComponent(radbtn_4)
                    .addComponent(radbtn_5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_no_cancel)
                    .addComponent(btn_yes_accept))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_no_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_no_cancelActionPerformed
        this.dispose();
        
    }//GEN-LAST:event_btn_no_cancelActionPerformed

    private void btn_yes_acceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_yes_acceptActionPerformed
        this.setTitle("Valoració");
        if(this.btn_yes_accept.getText().equals("Si")){
            this.radbtn_1.setVisible(true);
            this.radbtn_2.setVisible(true);
            this.radbtn_3.setVisible(true);
            this.radbtn_4.setVisible(true);
            this.radbtn_5.setVisible(true);
            this.btn_yes_accept.setText("Aceptar");
            this.btn_no_cancel.setText("Cancelar");
        }
        else{
            //guarda la valoracion de el episodio
            //this.btn_group.getSelection().getSelectedObjects();
            this.dispose();
        }
    }//GEN-LAST:event_btn_yes_acceptActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btn_group;
    private javax.swing.JButton btn_no_cancel;
    private javax.swing.JButton btn_yes_accept;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton radbtn_1;
    private javax.swing.JRadioButton radbtn_2;
    private javax.swing.JRadioButton radbtn_3;
    private javax.swing.JRadioButton radbtn_4;
    private javax.swing.JRadioButton radbtn_5;
    // End of variables declaration//GEN-END:variables
}
